#!/bin/bash

SCRIPT=$(readlink -f "$0")
PWD=$(dirname "$SCRIPT")
X4=`find ~ -iname "X4" -printf %h -quit`

echo "# script generated by $SCRIPT
PWD = \"$PWD\"
X4 = \"$X4\"
SRC = \"$PWD/src\"
MODS = \"$PWD/mods\"
" > $PWD/config.py
